services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: "minio"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  zookeeper:
    image: bitnami/zookeeper:3
    container_name: "zookeeper"
    platform: linux/amd64 #환경에 따라 불필요
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.5.1
    container_name: "kafka"
    platform: linux/amd64 #환경에 따라 불필요
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
    ports:
      - "9092:9092"

  ffmpeg-worker:
    image: jrottenberg/ffmpeg:5.1-ubuntu
    container_name: "ffmpeg-worker"
    depends_on:
      - kafka
      - minio
    volumes:
      - ./worker:/worker
      - ./videos:/videos
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=video-tasks
    command: bash -c "pip install kafka-python && apt update && apt install -y ffmpeg mc && python ./sh/ffmpeg/worker.py"

volumes:
  minio-data:
