spring:
  autoconfigure:
    exclude:
  datasource: #임시
    url: jdbc:h2:mem:proddb
    username: sa
    password:
    driver-class-name: org.h2.Driver
logging:
  level:
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
    com.back: INFO
custom:
  site: # 임시입니다
    cookieDomain: fivelogic.com
    frontUrl: "https://fivelogic.vercel.app"
    backUrl: "https://api.fivelogic.com"
    name: fivelogic