spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  datasource: #임시
    url: jdbc:h2:mem:proddb
    username: sa
    password:
    driver-class-name: org.h2.Driver
logging:
  level:
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
    com.back: INFO
custom:
  site: # 임시입니다
    cookieDomain: ""
    frontUrl: "http://13.124.192.14:8080"
    backUrl: "http://13.124.192.14:8080"
  cookie:
    httpOnly: true
    secure: false
    sameSite: "Lax"
    maxAge: "#{60*60*24}"