server:
  port: 8080
  forward-headers-strategy: native

sentry:
  dsn: https://2c0d2da223ce1abb9fa4ed3faaf01955@o4510117752471552.ingest.us.sentry.io/4510118514589696
  traces-sample-rate: 1.0
  send-default-pii: true


spring:
  application:
    name: back
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  output:
    ansi:
      enabled: always
  datasource: #?????? ??
    hikari:
      auto-commit: false
  h2: #H2 ??????(???)
    console:
      enabled: true
      path: /h2-console
  jackson: #?? ??
    serialization:
      fail-on-empty-beans: false
  jpa: #JPA ??
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

springdoc: #Swagger ??
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: DEBUG
management: #????
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
custom: # ??? ??
  site: # ?? ?? ?? (??? ?? ????? ??)
    cookieDomain: localhost
    frontUrl: "http://localhost:3000"
    backUrl: "http://localhost:8080"
    name: fivelogic
  jwt:
    secretKey: ${CUSTOM__JWT__SECRET_KEY:mySecretKey1234567890abcdefghijklmnopqrstuvwxyz}
  accessToken:
    expirationSeconds: "#{60*60*24}"  # 24??
  refreshToken:
    expirationSeconds: "#{60*60*24*7}"  # 7?
  cookie:
    httpOnly: true
    secure: false      # ??????? false, ??????? true
    sameSite: "Lax"
    maxAge: "#{60*60*24}"  # 24??
