# 워크플로우 이름
name: 이슈 자동화

# 실행 조건: 이슈가 열렸을 때
on:
  issues:
    types: [ opened ]

# 실행할 작업
jobs:
  automate-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      # 이슈 제목에 따라 Label 자동 할당 (예시)
      - name: feat 라벨 할당
        if: contains(github.event.issue.title, 'feat')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: feat
          
      - name: fix 라벨 할당
        if: contains(github.event.issue.title, 'fix')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: fix
          
      - name: refactor 라벨 할당
        if: contains(github.event.issue.title, 'refactor')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: refactor
          
      - name: chore 라벨 할당
        if: contains(github.event.issue.title, 'chore')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: chore

      - name: test 라벨 할당
        if: contains(github.event.issue.title, 'test')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: test

      # 이슈를 연 사람을 assignee로 자동 할당
      - name: 이슈 작성자를 assignee로 할당
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: ${{ github.event.issue.user.login }}

      # '프로젝트'의 'Backlog' 컬럼에 자동 추가
      - name : Github 프로젝트에 추가
        uses: jinhokim98/project-flow-add-issue-to-project@v1
        with:
          github_token: ${{ secrets.PROJECT_ACCESS_TOKEN }}
          project_owner: prgrms-web-devcourse-final-project
          project_number: 156
          target_column: 'Backlog'
